os: Visual Studio 2015

environment:
  matrix:
    - CLI_VERSION: Latest
    
install:
  # Download install script to install .NET cli in .dotnet dir
  - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - ps: dotnet --info

  # Build
  - ps: cd src/CoreDataLayer
  - ps: dotnet restore
  - ps: dotnet --verbose build
  
  # Pack
  - ps: dotnet pack --output './'
  
version: 0.0.1.{build}
