os: Visual Studio 2015

services: 
  - mssql2016
  - mysql
  - postgresql95
  
environment:
  matrix:
    - CLI_VERSION: Latest
    
install:
  # Download install script to install .NET cli in .dotnet dir
  - $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  - $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - dotnet --info

  # Build
  - cd src\CoreDataLayer
  - dotnet restore
  - dotnet build
  
  # Pack
  - dotnet pack --output './'

test_script:
  - cd ..\..\test\CoreDataLayer.Tests
  
  # Setup MySql
  - $env:MYSQL_PWD="Password12!"
  - $cmd = '"C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "create database TestDatabase;" --user=root'
  - iex "& $cmd"
  
  # Setup Postgres
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.3\bin\;%PATH%
  - createdb TestDatabase
  
  # Run tests
  
  - dotnet restore
  - dotnet test
  
artifacts:
  - path: '**\*.nupkg'
    name: Nuget Spec

version: CI.{build}