os: Visual Studio 2015

services: 
  - mssql2016
  - mysql
  - postgresql95
  
environment:
  matrix:
    - CLI_VERSION: Latest
    
install:
  # Download install script to install .NET cli in .dotnet dir
  - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - ps: dotnet --info

  # Build
  - ps: cd src\CoreDataLayer
  - ps: dotnet restore
  - ps: dotnet build
  
  # Pack
  - ps: dotnet pack --output './'

test_script:
  - ps: cd ..\..\test\CoreDataLayer.Tests
  
    # Setup MySql
  - ps: $env:MYSQL_PWD="Password12!"
  - ps: $cmd = '"C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "create database TestDatabase;" --user=root'
  - ps: iex "& $cmd"
  
  # Setup Postgres
  - ps: SET PGUSER=postgres
  - ps: SET PGPASSWORD=Password12!
  - ps: & 'C:\Program Files\PostgreSQL\9.5\bin\' createdb TestDatabase
  
  # Run tests
  
  - ps: dotnet restore
  - ps: dotnet test
  
artifacts:
  - path: '**\*.nupkg'
    name: Nuget Spec

version: CI.{build}